### ISSUE TITLE
ST_README.md outdated

### ISSUE THREAD

**Issue by KnoerleMan** [STMicroelectronics/cmsis-core#2] opened 2022-11-04 08:42 UTC
The compatibility information in the "ST_README.md" file is outdated and should be corrected asap!
It is only listed up to v5.4.0 but v5.6.0 has been released for more than 2 years.
Thanks.

**Comment by ASELSTM** [comment] 2022-11-21 12:08
Hi @KnoerleMan,

Thank you for pointing this out. This has been fixed and  **v5.6.0** is now listed within the  _ST_README.md_ file  in the frame of this [commit](https://github.com/STMicroelectronics/cmsis_core/commit/fe753d6310ce880143202ab71f37a6bafd17b63c).

Please allow me thus to close this thread as the issue is fixed now. Thank you for your contribution.

With regards,

**Closed as completed by ASELSTM** 2022-11-21 12:08 UTC
Labels: bug, documentation
